# Basic Information 
title: Zachary Porat
position: PhD Candidate in Mathematics
affiliation: Wesleyan University
affiliation_link: https://www.wesleyan.edu/mathcs/
email: zporat@wesleyan.edu

blog_title: A Mostly Mathematical Travelogue

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: zack porat, zachary porat, zachary porat math, zack porat math, zachary porat wesleyan, zack porat wesleyan, zachary porat modular forms, zack porat modular forms 
description: Zachary Porat is a PhD candidate in mathematics at Wesleyan University.  His research interests lie in number theory.  His advisor is David Pollack.
blog_description: A blog about mostly mathematical travels. 
canonical: zporat.github.io

# Links 
# If you don't need one of them, you may delete the corresponding line.
cv_link: /files/Porat_CV.pdf
google_scholar: https://scholar.google.com/citations?hl=en&user=vfhhsqUAAAAJ

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/Z_p.png
favicon_dark: ./assets/img/Z_p.png

# Footnote
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Sans Serif" # or "Sans Serif"

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# Plugins
plugins:
  - jekyll-feed

feed:
  url: https://zporat.github.io/blog.html
  title: A Mostly Mathematical Travelogue
  subtitle: A blog about mostly mathematical travels. 


# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
